version: '3'
services:
  node:
    restart: always
    build: .
    ports:
      - 5000:5000
    networks:
      - healthapp
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/health
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    networks:
      - healthapp

networks:
  healthapp:

volumes:
  mongodb: